blueprint:
  name: Калибровка термоголовки TRV-M2Z на основе внешнего датчика температуры
  description: Автоматическая калибровка температуры термоголовки TRV-M2Z на основе показаний внешнего датчика температуры.
  domain: automation
  input:
    external_temp:
      name: Выберите внешний датчик температуры
      description: Список внешних датчиков температуры используемых как источник показаний температуры.
      selector:
        entity:
          domain:
          - sensor
          device_class:
          - temperature
          multiple: false
    climate_names:
      name: Выберите термоголовку TRV-M2Z
      description: Список термоголовок.
      selector:
        entity:
          domain:
          - climate
          multiple: true
    offset_factor:
      name: Коэффициент коррекции
      description: >
        Добавляет взвешенную разницу между текущей и целевой температурой.
        Формула: коэффициент * (фактическая температура - целевая температура).
    
        При следующих значениях
        0   — коррекция не применяется (калибровка основывается только на разнице между показаниями внешнего датчика температуры и внутреннего датчика терморегулятора);
        0.5 — частичная компенсация отклонения (используется половина разницы между показаниями внешнего датчика и внутренним датчиком терморегулятора, с учётом заданной температуры);
        1   — полная компенсация отклонения (калибровка учитывает всю разницу между показаниями внешнего датчика и внутренним датчиком терморегулятора, с учётом заданной температуры).

        Значения больше 1 усиливают коррекцию, а меньше 1 — смягчают её (максимальное значение 2).
      default: 0
      selector:
        number:
          min: 0
          max: 2
          step: 0.1
  source_url: https://github.com/bibibi-Matrix/calibrate_beok_trv/blob/main/blueprints/calib_trv_external_temp.yaml
alias: Калибровка термоголовки TRV-M2Z
description: ''
variables:
  climate_names: !input climate_names
  external_temperature: !input external_temp
  offset_factor: !input offset_factor
trigger:
- platform: state
  entity_id: !input external_temp
  for:
    hours: 0
    minutes: 0
    seconds: 15
    milliseconds: 0
- platform: state
  entity_id: !input climate_names
  for:
    hours: 0
    minutes: 0
    seconds: 15
    milliseconds: 0
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{ states(external_temperature) != ''unavailable'' }}'
  - condition: template
    value_template: '{{ states(external_temperature) != ''unknown'' }}'
action:
- repeat:
    for_each: "{{ climate_names }}"
    sequence:
    - variables:
        climate_name: "{{ repeat.item }}"
        device_calib: "number.{{ climate_name.removeprefix('climate.') }}_local_temperature_calibration"
        external_temp: "{{ states(external_temperature) | float() }}"
        local_temp: "{{ state_attr(climate_name, 'current_temperature') | float() }}"
        target_temp: "{{ state_attr(climate_name, 'temperature') | float() }}"
        actual_calib: "{{ states(device_calib) | float() }}"
        temp_diff: "{{ external_temp - target_temp }}"
        calibration_offset: "{{ temp_diff * offset_factor }}"
        target_calib: "{{ external_temp - (local_temp - actual_calib) + calibration_offset }}"
        target_calib_round: "{{ target_calib | round() }}"
        target_calib_trunc: "{{ [ ([target_calib_round, 9] | min), -9 ] | max }}"

    - alias: "check if calibration needs change"
      condition: template
      value_template: "{{ (actual_calib | round()) != target_calib_trunc }}"
      
    - service: number.set_value
      target:
        entity_id: "{{ device_calib }}"
      data:
        value: "{{ target_calib_trunc }}"

- delay: 5
mode: single
max_exceeded: silent
